// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYkRtfyljjsSfokrKYj_oVUjx39ufQVzY',
    appId: '1:346664368301:web:ee1abfbb79652f2cceee24',
    messagingSenderId: '346664368301',
    projectId: 'crud-productos-235f1',
    authDomain: 'crud-productos-235f1.firebaseapp.com',
    storageBucket: 'crud-productos-235f1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7QqKB35StAv8UV-yHTaFT_kyow-tZUcI',
    appId: '1:346664368301:android:819ef1c4694f6020ceee24',
    messagingSenderId: '346664368301',
    projectId: 'crud-productos-235f1',
    storageBucket: 'crud-productos-235f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDv5bKdnPZ7JjnPxP3LVO3f74QRD-t9tuU',
    appId: '1:346664368301:ios:4ba74a27918f4eeaceee24',
    messagingSenderId: '346664368301',
    projectId: 'crud-productos-235f1',
    storageBucket: 'crud-productos-235f1.appspot.com',
    iosBundleId: 'com.example.crudFirebase',
  );
}
